### ISSUE TITLE
Prepare plugin for Caddy v2

### ISSUE THREAD

**Issue by mholt** [okkur/gomods#8]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Caddy 2 is in beta and will soon be the new stable release

**What you expected to happen**:
It would be awesome if this plugin worked for Caddy 2.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:
I can help provide tips for transitioning the plugin to Caddy 2. Eventually we will have a transition guide, so you could wait until this. For now, there's this wiki page: https://github.com/caddyserver/caddy/wiki/v2:-Writing-a-Module

Since Caddy 2 is still in beta, some minor things about plugin authorship may change, but for the most part things are looking pretty good.

Not urgent, but would be nice to have within a few months or so. Let me know if I can answer any questions!

**Environment**:
- Gomods version:  
- Others:

**Comment by erbesharat** [comment]
Since we have to keep the v1 version too, is it better to keep the v2 version under a subpackage or it fits better in a separate branch?
CC: @stp-ip

**Comment by stp-ip** [comment]
@mholt any recommendations from the caddy side of things?

Go module wise I think a subpackage is the recommendation.

**Comment by mholt** [comment]
Well, Go doesn't have "subpackages" so I don't really know what you mean by that...

I think the answer depends on how you want to manage your repo and how long you want to support Caddy 1.

If it were me, I'd probably replace the v1 with the v2 implementation entirely, and tag v2.0.0. You could continue to maintain v1 on the v1.x.x tree, and v2 on master and all future tags.
